apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend
  namespace: backstage
  labels:
    app: backstage-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backstage-backend
  template:
    metadata:
      labels:
        app: backstage-backend
    spec:
      serviceAccountName: backstage
      imagePullSecrets:
        - name: docker
      containers:
        - name: backstage-backend
          image: europe-west3-docker.pkg.dev/hd-backstage-poc-28107/backstage-96b1cd00/backstage/backend:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: BACKSTAGE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_host
            - name: BACKSTAGE_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_port
            - name: BACKSTAGE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_user
            - name: BACKSTAGE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_pass
