apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backstage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      imagePullSecrets:
        - name: docker
      containers:
        - name: backend
          image: europe-west3-docker.pkg.dev/hd-backstage-poc-28107/backstage-96b1cd00/backstage/backend:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: BACKSTAGE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_host
            - name: BACKSTAGE_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_port
            - name: BACKSTAGE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_user
            - name: BACKSTAGE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backstage-db-credentials
                  key: db_pass
