apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-backend
  namespace: backstage
  labels:
    app: backstage-backend
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: backstage-backend
    networking.gke.io/managed-certificates: backstage-backend
    networking.gke.io/v1beta1.FrontendConfig: backstage-backend-redirect
spec:
  defaultBackend:
    service:
      name: backstage-backend
      port:
        number: 7007
