apiVersion: v1
kind: Service
metadata:
  name: backstage-backend
  namespace: backstage
  labels:
    app: backstage-backend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: backstage-backend
  ports:
    - protocol: TCP
      port: 7007
      targetPort: 7007
