# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: backstage-core
#   description: Developer Experience Platform
#   # Example for optional annotations
#   # annotations:
#   #   github.com/project-slug: backstage/backstage
#   #   backstage.io/techdocs-ref: dir:.
# spec:
#   type: service
#   owner: dev@breu.io
#   lifecycle: poc 
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage
  namespace: backstage
spec:
  targets:
    - ./packages/app/catalog-info.yaml
    - ./packages/backend/catalog-info.yaml
    - ./infra/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  namespace: backstage
spec:
  owner: breu-dev
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: breu-dev
  namespace: backstage
  description: Breu.io Vendor Team
spec:
  type: team
  profile:
    displayName: HD Team @ Breu
    email: hd@breu.io
  children: []