version: '3.7'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:  # this is the default
      - backstage-db-data:/var/lib/postgresql/data
    networks:
      - backstage-network
    restart: always

networks:
  backstage-network: {}

volumes:
  backstage-db-data: {}