apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-network-55f14ee8
  title: Backstage Network
  description: Backstage Database
spec:
  type: network
  owner: breu
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-network-peering-address-55f14ee8
  title: Backstage Network Peering Address
  description: Backstage Database
spec:
  type: ip
  owner: breu
  system: backstage
  dependsOn:
    - resource:backstage-network-55f14ee8
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-poc-35e94176
  title: Backstage Database
  description: Backstage Database
spec:
  type: database
  owner: breu
  system: backstage
  dependsOn:
    - resource:backstage-network-55f14ee8
    - resource:backstage-network-peering-address-55f14ee8
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-cluster-55f14ee8
  description: Backstage Kubernetes Cluster
spec:
  type: cluster
  owner: breu
  system: backstage
  dependsOn:
    - resource:backstage-network-55f14ee8
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-backend-certificate
  description: Backstage SSL Certificate
spec:
  type: certificate
  owner: breu
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-backend-loadbalancer-address-55f14ee8
  description: Backstage Database
spec:
  type: ip
  owner: breu
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: loadbalancer
  description: Backstage LoadBalancer for Kubernetes Cluster
spec:
  type: loadbalancer
  owner: breu
  system: backstage
  dependsOn: 
    - resource:backstage-backend-loadbalancer-address-55f14ee8
    - resource:backstage-backend-certificate
    - resource:backstage-cluster-55f14ee8