apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  namespace: backstage
  title: Backend for Backstage
  description: Backend for Backstage
  annotations:
  tags: 
    - typescript
    - service
spec:
  type: service
  owner: backstage/breu-dev
  lifecycle: poc
  dependsOn:
    - resource:backstage/backstage-poc-35e94176
    - resource:backstage/backstage-cluster-55f14ee8
    - resource:backstage/backstage-backend-certificate
    - resource:backstage/loadbalancer
  system: backstage/backstage