apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  namespace: backstage
  title: Backend for Backstage
  description: Backend for Backstage
  annotations:
  tags: 
    - typescript
    - service
spec:
  type: service
  owner: backstage/breu-dev
  lifecycle: poc
  dependsOn:
    - resource:backstage/database
    - resource:backstage/cluster
  system: backstage/backstage