apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: ${backstage__backend__certificate__name}
  namespace: ${backstage__namespace__name}
  labels:
%{ for key, value in backstage__backend__labels ~}
    ${key}: ${value}
%{ endfor ~}
spec:
  domains:
    - ${backstage__backend__certificate__domain}
