apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: ${metadata_name}
  namespace: ${metadata_namespace}
  labels:
%{ for key, value in resource_labels ~}
    ${key}: ${value}
%{ endfor ~}
spec:
  domains:
    - ${certificate_domain}
