apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${backstage__backend__hpa__name}
  namespace: ${backstage__namespace__name}
  labels:
%{ for key, value in backstage__backend__labels ~}
    ${key}: ${value}
%{ endfor ~}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${backstage__backend__deployment__name}
  minReplicas: 3
  maxReplicas: 128
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
        # target:
        #   type: AverageValue
        #   averageValue: 384Mi
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180 # scale down slowly
      policies:
        - type: Percent
          value: 200 # Half of the pods are scaled down
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 30 # scale up quickly
      policies:
        - type: Percent
          value: 400 # 4 x the pods are scaled up
          periodSeconds: 5
      selectPolicy: Max
