apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ${metadata_name}
  namespace: ${metadata_namespace}
  labels:
    ${resource_labels}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
