apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${metadata_name}
  namespace: ${metadata_namespace}
  labels:
    ${resource_labels}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ${metadata_name}
    networking.gke.io/managed-certificates: ${metadata_name}
    networking.gke.io/v1beta1.FrontendConfig: ${metadata_name}
spec:
  defaultBackend:
    service:
      name: ${metadata_name}
      port:
        number: 7007
