apiVersion: v1
kind: Service
metadata:
  name: ${backstage__backend__service__name}
  namespace: ${backstage__namespace__name}
  labels:
%{ for key, value in backstage__backend__labels ~}
    ${key}: ${value}
%{ endfor ~}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
%{ for key, value in backstage__backend__labels ~}
    ${key}: ${value}
%{ endfor ~}
  ports:
    - port: ${backstage__backend__service__port}
      targetPort: ${backstage__backend__container__port}
